name: champion_api
description: A Dart library for mocking Deriv trading API responses, designed for testing and development.
version: 1.0.0
# repository: https://github.com/yourusername/champion_api

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  http: ^1.1.0
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  mockito: ^5.4.2
